### ISSUE TITLE
Branches and git colors

### ISSUE THREAD

**Issue by svenkeidel** [jeffWelling/ticgit#36]
`[color] ui = always` in gitconfig causes several errors.

The branchnames contains the shell color sequences: `\e[32mmaster\e[m`. If I turn the colors off, i get the plain `master` branchlable.

Greetings Sven

P.S.: I'll post this issue to the git-gem issue list, because I think it's better to solve the bug there.

P.P.S.: There is already a ticket.

**Comment by jeffWelling** [comment]
Hey jungerkrieger89,

I'm not sure if the git gem is maintained anymore, for other bugs that we've encountered in it we've had to apply monkey patches at the beginning of the ticgit source files.
I'm looking into it today, and am going to be looking at creating a similar monkey patch if need be.

Cheers,
Jeff.

**Comment by jeffWelling** [comment]
@jungerkrieger89
So I've pondered the issue for awhile now and I think the best way to approach this bug is to add a note in the documentation about using `[color] ui = true` instead of `[color] ui = always` where possible, and to make a best effort to upgrade to one of the newer gems and away from the long deprecated git gem.  I don't expect said upgrade to happen in the immediate future, but I will post an update to this issue when I have.
Cheers,
Jeff.

**Comment by jeffWelling** [comment]
I've added a note in the README so that at least the upstream bug is documented, and noting that the plan is to move away from the git gem entirely, so I'm going to close this issue now.

**Comment by svenkeidel** [comment]
thanks for help, +1 for ticgit
