### ISSUE TITLE
ti command fails on Windows after clean install

### ISSUE THREAD

**Issue by AArnott** [jeffWelling/ticgit#49]
I installed [Ruby 1.9.3](http://rubyinstaller.org/downloads/)
Then ran `gem install TicGit-ng` at the command line.
Then ran `ti --help` and got this:

```
C:/Ruby193/lib/ruby/gems/1.9.1/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng.rb:18: Use RbConfig instead of obsolete and deprecated Config.
C:/Ruby193/lib/ruby/gems/1.9.1/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:257:in `trap': unsupported signal SIGWINCH (ArgumentError)
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:257:in `<top (required)>'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng.rb:37:in `<top (required)>'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/TicGit-ng-1.0.2.14/bin/ti:11:in `<top (required)>'
        from C:/Ruby193/bin/ti:23:in `load'
        from C:/Ruby193/bin/ti:23:in `<main>'
```

No idea where to go from here.

**Comment by jeffWelling** [comment]
Hm.  After some investigating it seems like SIGWINCH is an unsupported signal on Windows operating systems, and I'm having trouble finding out what the Windows equivalent is or the best way to resolve this. While I continue to try and work this out, can you post your operating system (Win 7, Win XP, ....)?

Due to the relationship between SIGWINCH and the detection of changes in the window size, searching for 'sigwinch windows' and other search phrases isn't producing many helpful results so I'm trying stackoverflow.

**Comment by AArnott** [comment]
Thanks for investigating. I'm on Windows 8.

Sent from my Windows Phone

**Comment by jeffWelling** [comment]
According to the only answer (as of yet) on Stackoverflow, it looks like there _is_ a way of detecting window size changes, but it looks convoluted and too complicated, and to be honest I'm not sure why TicGit-ng needs to be aware of the window size changing. I'm just the current maintainer and not the person who wrote that part of the code, but I can't think of any part of TicGit-ng that should really _need_ to be aware of window size changes.  I'm probably going to explore just removing that part of the code because I see little gain from it as it stands right now. Updates to come.

http://stackoverflow.com/questions/10856926/sigwinch-equivalent-on-windows/10857339#10857339 If your interested.

**Comment by jeffWelling** [comment]
I have a potential fix but I was wondering if you would help me test it out before I publish it via rubygems. If I emailed you a gem could you temporarily install it to test it out with me?

**Comment by AArnott** [comment]
I'd be very happy to!

On Thursday, June 14, 2012, Jeff Welling wrote:

> I have a potential fix but I was wondering if you would help me test it
> out before I publish it via rubygems. If I emailed you a gem could you
> temporarily install it to test it out with me?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jeffWelling/ticgit/issues/49#issuecomment-6348361

## 

## 

Andrew Arnott
"I [may] not agree with what you have to say, but I'll defend to the death
your right to say it." - S. G. Tallentyre

**Comment by jeffWelling** [comment]
I think I've resolved this particular bug, but in the process I've found that without a default command line editor, another bug may have to be filed for input on Windows.  Regardless, I'll email you the zip of the current fix so you can verify that we've resolved the issue at hand for you.

**Comment by AArnott** [comment]
Thanks.  Now I'm seeing this:

```
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find TicGit-ng (>= 0) amongst [bigdecimal-1.1.0, git-1.2.5, io-console-0.3, json-1.5.4, minitest-2.5.1, rake-0.9.2.2, rdoc-3.9.4] (Gem::LoadError)
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:256:in `to_spec'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems.rb:1231:in `gem'
        from C:/Users/Andrew/Downloads/jeffWelling-ticgit-4ce1f5c/bin/ti:22:in `<main>'
```

**Comment by AArnott** [comment]
I should mention that I've very rusty at my ruby skills.  Am I simply missing some lib path?

**Comment by jeffWelling** [comment]
I honeslty don't know, I've never seen that error before and the output -- to me at least -- doesn't look very helpful in resolving whatever issue that is....

Try the gem that I just emailed you and see if you still get that error message.  We may need to put on our investigative hats for some good ol' fashioned magnifying-glass-ing ;)

Cheers,
Jeff.

**Comment by jeffWelling** [comment]
Also, if you do have trouble with a command line editor on windows, check this out; http://stackoverflow.com/questions/10564/how-can-i-set-up-an-editor-to-work-with-git-on-windows

**Comment by AArnott** [comment]
It seems to be all working now.  Thanks!

**Comment by jeffWelling** [comment]
Excellent. If you have any more problems, you know where to come for help :)
