### ISSUE TITLE
"$ ti attach" -error-dump in Ubuntu

### ISSUE THREAD

**Issue by heoa** [jeffWelling/ticgit#63]
$ ti attach
/var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/command.rb:29:in `const_get': no such file to load -- ticgit-ng/command/attach (LoadError)
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/command.rb:29:in`get'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:45:in `execute!'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:9:in`execute'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/bin/ti:13
    from /usr/local/bin/ti:19:in `load'
    from /usr/local/bin/ti:19

**Comment by jeffWelling** [comment]
This should be resolved in the latest version of TicGit-ng, please update and let me know if this resolves the problem for you. In the meantime I will mark the issue as resolved.

**Comment by heoa** [comment]
With debian:

$ ti attach
/usr/lib/ruby/1.8/git/lib.rb:643:in `command': git branch -a 2>&1:fatal: Failed to resolve HEAD as a valid ref. (Git::GitExecuteError)
    from /usr/lib/ruby/1.8/git/lib.rb:615:in`command_lines'
    from /usr/lib/ruby/1.8/git/lib.rb:209:in `branches_all'
    from /usr/lib/ruby/1.8/ticgit/base.rb:241:in`load_tickets'
    from /usr/lib/ruby/1.8/ticgit/base.rb:72:in `reset_ticgit'
    from /usr/lib/ruby/1.8/ticgit/base.rb:38:in`initialize'
    from /usr/lib/ruby/1.8/ticgit.rb:25:in `new'
    from /usr/lib/ruby/1.8/ticgit.rb:25:in`open'
    from /usr/lib/ruby/1.8/ticgit/cli.rb:23:in `initialize'
    from /usr/lib/ruby/1.8/ticgit/cli.rb:16:in`new'
    from /usr/lib/ruby/1.8/ticgit/cli.rb:16:in `parse'
    from /usr/lib/ruby/1.8/ticgit/cli.rb:12:in`execute'
    from /usr/bin/ti:10
$ 

$ dpkg -l ticgit
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                       Version                    Description
+++-==========================-==========================-====================================================================
ii  ticgit                     0.3.3-2                    ticketing system built on Git
$ 

Perhaps this is not the ticgit-ng?

**Comment by jeffWelling** [comment]
As highlighted in other issues you have filed, it seems that your problems are with TicGit instead of TicGit-ng, so I advise that you either A) Switch to TIcGit-ng instead, or B) begin filing issues on the TIcGit page, but be warned that TicGit has been stagnant for several years and I don't expect the original author to return any time soon.

**Comment by jeffWelling** [comment]
I will add that to uninstall the TicGit gem and install the TicGit-ng gem, assuming you installed TicGit as a gem, is to do this;

```
gem uninstall ticgit
gem install TicGit-ng
```

This will remove the TicGit gem and install the TicGit-ng gem, and should resolve many of the problems that you seem to be having.  It is important that you remove TicGit before installing TIcGit-ng because they use the same name for their primary executable, so having them both installed means that trying to run the program could result in either version being called.
