### ISSUE TITLE
Version -number command?

### ISSUE THREAD

**Issue by heoa** [jeffWelling/ticgit#65]
Hello,
I have been debugging now older versions of ticgit (not knowing which version actually) so I would like to know how to get the version number (hopefully containing date)?

For example, I got this error msg [1] with some older Ticgit -version. Now I would like to have some dump that would precisely show the version.  Ideas how to get it?

_P.s. this may be just reinventing the wheel, there may be some info in /proc or something like that where I could find the info about the version, currently not just finding it -- so making debugging now in the case of emergency time-comsuming, found some good article about numbers [2]._

[1] http://pastie.org/4224646
[2] http://www.codinghorror.com/blog/2007/02/whats-in-a-version-number-anyway.html

**Comment by jeffWelling** [comment]
The last version of the TicGit (not TicGit-ng) gem was published as "0.3.6", but I have no idea which commit in the repository that maps to, and since the code itself from that time doesn't seem to include any version numbers that I found in my brief check of that repo, I don't think there is any way to tell.

I'm afraid I can't help you with problems if they aren't related to TicGit-ng, for problems related to other projects (including TicGit) you should file bugs on the appropriate bug trackers. 

That link is a good read, but changing the version numbering scheme again isn't something I will be doing in the near future, not to mention using dates doesn't make sense for TicGit-ng right now when there are several releases per year, sometimes even per day. I do appreciate the input though! :)

[Update] This might be of use to you, it seems to relate the version number to the commit and subsequently the date.  https://github.com/schacon/ticgit/blob/bf57b032e030bd16a7b2bb3e95ee007b17147759/ticgit.gemspec

**Comment by heoa** [comment]
Hey, 
why don't you add a version-number -command like `tic --version` to see which version of Ticgit people are using?

Now I understood so yes it is not apparently needed, current version ticgit ?!...investigating...

$ dpkg -l ticgit
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                       Version                    Description
+++-==========================-==========================-====================================================================
ii  ticgit                     0.3.3-2                    ticketing system built on Git

**Comment by jeffWelling** [comment]
If you have an issue with TicGit then please  file a new issue on the appropriate page. TicGit-ng already has a version argument that will print out the TicGit-ng version number.
