### ISSUE TITLE
ticgit ubuntu 12.04 package broken!?

### ISSUE THREAD

**Issue by ant11** [jeffWelling/ticgit#73]
Hi, just installed the ticgit and ticgitweb via:

   sudo apt-get install ticgit ticgitweb

Then I created a test git repo, entered it and tried to execute ti:

   mkdir test
   cd test
   git init
   ti --help

but that throws:

/usr/lib/ruby/vendor_ruby/git/lib.rb:700:in `command': git log "--pretty=raw" "--no-color" "-1" "ticgit"  2>&1:fatal: ambiguous argument 'ticgit': unknown revision or path not in the working tree. (Git::GitExecuteError)
Use '--' to separate paths from revisions
    from /usr/lib/ruby/vendor_ruby/git/lib.rb:672:in`command_lines'
    from /usr/lib/ruby/vendor_ruby/git/lib.rb:92:in `full_log_commits'
    from /usr/lib/ruby/vendor_ruby/git/log.rb:108:in`run_log'
    from /usr/lib/ruby/vendor_ruby/git/log.rb:101:in `check_log'
    from /usr/lib/ruby/vendor_ruby/git/log.rb:84:in`each'
    from /usr/lib/ruby/vendor_ruby/ticgit-ng/base.rb:25:in `map'
    from /usr/lib/ruby/vendor_ruby/ticgit-ng/base.rb:25:in`initialize'
    from /usr/lib/ruby/vendor_ruby/ticgit-ng.rb:46:in `new'
    from /usr/lib/ruby/vendor_ruby/ticgit-ng.rb:46:in`open'
    from /usr/lib/ruby/vendor_ruby/ticgit-ng/cli.rb:24:in `initialize'
    from /usr/lib/ruby/vendor_ruby/ticgit-ng/cli.rb:14:in`new'
    from /usr/lib/ruby/vendor_ruby/ticgit-ng/cli.rb:14:in `parse'
    from /usr/lib/ruby/vendor_ruby/ticgit-ng/cli.rb:9:in`execute'
    from /usr/bin/ti:12

Are the official ticgit packages broken or something else wrong?
thanks

**Comment by jeffWelling** [comment]
Can you please copy paste the output of `ti --version`.

I suspect that the version of TicGit-ng that exists as 'ticgit' in the Debian apt repository has fallen out of date.  I just recently resolved this bug and pushed out the fix in the latest gem, 1.0.2.16.

You have two options.  A) Contact the maintainer of the 'ticgit' apt package and request that he update the package, or B) you can uninstall the 'ticgit' package and reinstall the gem which will give you the latest version of TicGit-ng. 

To install the TicGit-ng gem just do `gem install TicGit-ng`.  At present, the TicGit-ng gem includes the TicgitWeb program as well.

Also, just so you know, it is an error to try and use the git repository before there are any commits in it. The latest version of TicGit-ng should fail gracefully with an appropriate informational notice stating the same thing, but just so you know.

Thanks for taking the time to file the bug, I'm going to mark this as closed because I'm 80% sure the problem here is that the 'ticgit' debian apt package is outdated, but the maintainer of the package is generally pretty good so if you just drop him a line letting him know the project has updated I'm sure he will be able to publish a package with the latest version in a day or two.  Given a couple weeks I'm sure the package will be updated on it's own, so you could also just wait it out, but who likes waiting ;)

Thanks again,
Jeff.

**Comment by ant11** [comment]
You were right. I installed it from gem and it works :-)

Only few ideas for improving the web gui:
- Use the user.name instead of user.email (or use user.name plus user.email) for "assigned" in the detailed ticket view
- use the user.name instead of the first part of user.email for "assigned column" in the ticket overview 
- add the possibility to remove a tag in the detailed ticket view

But anyways: cool stuff :-)

**Comment by jeffWelling** [comment]
Awesome! All top notch ideas, thanks for suggesting them, I'll see what I can do about cleaning up the web interface a bit.  It needs a lot of TLC in a lot of areas, areas that I'm not hugely proficient in, so it may take awhile but I am making progress :)
Thanks again!
